// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelAppointment = `-- name: CancelAppointment :one
UPDATE appointments
SET status = 'cancelled',
    cancellation_reason = $2,
    cancelled_at = $3
WHERE id = $1 AND status = 'booked'
RETURNING id, doctor_id, patient_id, starts_at, ends_at, status,
          cancellation_reason, cancelled_at, created_at, updated_at
`

type CancelAppointmentParams struct {
	ID                 uuid.UUID
	CancellationReason *string
	CancelledAt        *time.Time
}

func (q *Queries) CancelAppointment(ctx context.Context, arg CancelAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, cancelAppointment, arg.ID, arg.CancellationReason, arg.CancelledAt)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.PatientID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countUpcomingAppointmentsForPatient = `-- name: CountUpcomingAppointmentsForPatient :one
SELECT count(*)
FROM appointments
WHERE patient_id = $1
  AND status = 'booked'
  AND starts_at >= $2::timestamptz
`

type CountUpcomingAppointmentsForPatientParams struct {
	PatientID uuid.UUID
	FromTime  time.Time
}

func (q *Queries) CountUpcomingAppointmentsForPatient(ctx context.Context, arg CountUpcomingAppointmentsForPatientParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUpcomingAppointmentsForPatient, arg.PatientID, arg.FromTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (doctor_id, patient_id, starts_at, ends_at, status)
VALUES ($1, $2, $3, $4, 'booked')
RETURNING id, doctor_id, patient_id, starts_at, ends_at, status,
          cancellation_reason, cancelled_at, created_at, updated_at
`

type CreateAppointmentParams struct {
	DoctorID  uuid.UUID
	PatientID uuid.UUID
	StartsAt  time.Time
	EndsAt    time.Time
}

// Both ends of the interval are supplied by the caller rather than derived here.
// The domain owns slot arithmetic, and appointments_duration_check verifies the
// two agree, so the database still rejects a mismatched pair.
func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.DoctorID,
		arg.PatientID,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.PatientID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppointmentByID = `-- name: GetAppointmentByID :one
SELECT id, doctor_id, patient_id, starts_at, ends_at, status,
       cancellation_reason, cancelled_at, created_at, updated_at
FROM appointments
WHERE id = $1
`

func (q *Queries) GetAppointmentByID(ctx context.Context, id uuid.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointmentByID, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.PatientID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppointmentByIDForUpdate = `-- name: GetAppointmentByIDForUpdate :one
SELECT id, doctor_id, patient_id, starts_at, ends_at, status,
       cancellation_reason, cancelled_at, created_at, updated_at
FROM appointments
WHERE id = $1
FOR UPDATE
`

// Row lock taken at the start of every cancel/reschedule transaction. Because
// both flows lock exactly one appointment row and never a second one, there is
// no lock-ordering cycle and therefore no deadlock between them.
func (q *Queries) GetAppointmentByIDForUpdate(ctx context.Context, id uuid.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointmentByIDForUpdate, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.PatientID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAppointmentEvent = `-- name: InsertAppointmentEvent :exec
INSERT INTO appointment_events (appointment_id, event_type, from_starts_at, to_starts_at, source)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAppointmentEventParams struct {
	AppointmentID uuid.UUID
	EventType     AppointmentEventType
	FromStartsAt  *time.Time
	ToStartsAt    *time.Time
	Source        string
}

func (q *Queries) InsertAppointmentEvent(ctx context.Context, arg InsertAppointmentEventParams) error {
	_, err := q.db.Exec(ctx, insertAppointmentEvent,
		arg.AppointmentID,
		arg.EventType,
		arg.FromStartsAt,
		arg.ToStartsAt,
		arg.Source,
	)
	return err
}

const listAppointmentEvents = `-- name: ListAppointmentEvents :many
SELECT id, appointment_id, event_type, from_starts_at, to_starts_at, source, occurred_at
FROM appointment_events
WHERE appointment_id = $1
ORDER BY occurred_at ASC, id ASC
`

func (q *Queries) ListAppointmentEvents(ctx context.Context, appointmentID uuid.UUID) ([]AppointmentEvent, error) {
	rows, err := q.db.Query(ctx, listAppointmentEvents, appointmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppointmentEvent{}
	for rows.Next() {
		var i AppointmentEvent
		if err := rows.Scan(
			&i.ID,
			&i.AppointmentID,
			&i.EventType,
			&i.FromStartsAt,
			&i.ToStartsAt,
			&i.Source,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookedStartsForDoctorInRange = `-- name: ListBookedStartsForDoctorInRange :many
SELECT starts_at
FROM appointments
WHERE doctor_id = $1
  AND status = 'booked'
  AND starts_at >= $2::timestamptz
  AND starts_at < $3::timestamptz
ORDER BY starts_at ASC
`

type ListBookedStartsForDoctorInRangeParams struct {
	DoctorID   uuid.UUID
	RangeStart time.Time
	RangeEnd   time.Time
}

// Half-open [from, to) window, matching the interval convention used throughout.
func (q *Queries) ListBookedStartsForDoctorInRange(ctx context.Context, arg ListBookedStartsForDoctorInRangeParams) ([]time.Time, error) {
	rows, err := q.db.Query(ctx, listBookedStartsForDoctorInRange, arg.DoctorID, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []time.Time{}
	for rows.Next() {
		var starts_at time.Time
		if err := rows.Scan(&starts_at); err != nil {
			return nil, err
		}
		items = append(items, starts_at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingAppointmentsForPatient = `-- name: ListUpcomingAppointmentsForPatient :many
SELECT a.id, a.doctor_id, a.patient_id, a.starts_at, a.ends_at, a.status,
       a.cancellation_reason, a.cancelled_at, a.created_at, a.updated_at,
       d.slug AS doctor_slug, d.full_name AS doctor_full_name,
       d.specialty AS doctor_specialty, d.timezone AS doctor_timezone
FROM appointments a
JOIN doctors d ON d.id = a.doctor_id
WHERE a.patient_id = $1
  AND a.status = 'booked'
  AND a.starts_at >= $4::timestamptz
ORDER BY a.starts_at ASC, a.id ASC
LIMIT $2 OFFSET $3
`

type ListUpcomingAppointmentsForPatientParams struct {
	PatientID uuid.UUID
	Limit     int32
	Offset    int32
	FromTime  time.Time
}

type ListUpcomingAppointmentsForPatientRow struct {
	ID                 uuid.UUID
	DoctorID           uuid.UUID
	PatientID          uuid.UUID
	StartsAt           time.Time
	EndsAt             time.Time
	Status             AppointmentStatus
	CancellationReason *string
	CancelledAt        *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DoctorSlug         string
	DoctorFullName     string
	DoctorSpecialty    string
	DoctorTimezone     string
}

// "Upcoming" is defined against a caller-supplied instant so the query stays
// deterministic under test; (starts_at, id) makes the ordering total.
func (q *Queries) ListUpcomingAppointmentsForPatient(ctx context.Context, arg ListUpcomingAppointmentsForPatientParams) ([]ListUpcomingAppointmentsForPatientRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingAppointmentsForPatient,
		arg.PatientID,
		arg.Limit,
		arg.Offset,
		arg.FromTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingAppointmentsForPatientRow{}
	for rows.Next() {
		var i ListUpcomingAppointmentsForPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.DoctorID,
			&i.PatientID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.CancellationReason,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DoctorSlug,
			&i.DoctorFullName,
			&i.DoctorSpecialty,
			&i.DoctorTimezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleAppointment = `-- name: RescheduleAppointment :one
UPDATE appointments
SET starts_at = $2,
    ends_at = $3
WHERE id = $1 AND status = 'booked'
RETURNING id, doctor_id, patient_id, starts_at, ends_at, status,
          cancellation_reason, cancelled_at, created_at, updated_at
`

type RescheduleAppointmentParams struct {
	ID       uuid.UUID
	StartsAt time.Time
	EndsAt   time.Time
}

// Moving the row is what releases the old slot and claims the new one: the
// partial unique index sees a single UPDATE, so both halves are atomic.
func (q *Queries) RescheduleAppointment(ctx context.Context, arg RescheduleAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, rescheduleAppointment, arg.ID, arg.StartsAt, arg.EndsAt)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.PatientID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
