// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doctors.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDoctors = `-- name: CountDoctors :one
SELECT count(*)
FROM doctors
WHERE (NOT $1::boolean) OR is_active
`

func (q *Queries) CountDoctors(ctx context.Context, activeOnly bool) (int64, error) {
	row := q.db.QueryRow(ctx, countDoctors, activeOnly)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDoctorByID = `-- name: GetDoctorByID :one
SELECT id, slug, full_name, specialty, timezone, is_active, created_at, updated_at
FROM doctors
WHERE id = $1
`

func (q *Queries) GetDoctorByID(ctx context.Context, id uuid.UUID) (Doctor, error) {
	row := q.db.QueryRow(ctx, getDoctorByID, id)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.FullName,
		&i.Specialty,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDoctorBySlug = `-- name: GetDoctorBySlug :one
SELECT id, slug, full_name, specialty, timezone, is_active, created_at, updated_at
FROM doctors
WHERE slug = $1
`

func (q *Queries) GetDoctorBySlug(ctx context.Context, slug string) (Doctor, error) {
	row := q.db.QueryRow(ctx, getDoctorBySlug, slug)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.FullName,
		&i.Specialty,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDoctors = `-- name: ListDoctors :many
SELECT id, slug, full_name, specialty, timezone, is_active, created_at, updated_at
FROM doctors
WHERE (NOT $3::boolean) OR is_active
ORDER BY full_name ASC, id ASC
LIMIT $1 OFFSET $2
`

type ListDoctorsParams struct {
	Limit      int32
	Offset     int32
	ActiveOnly bool
}

func (q *Queries) ListDoctors(ctx context.Context, arg ListDoctorsParams) ([]Doctor, error) {
	rows, err := q.db.Query(ctx, listDoctors, arg.Limit, arg.Offset, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Doctor{}
	for rows.Next() {
		var i Doctor
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.FullName,
			&i.Specialty,
			&i.Timezone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkingHoursByDoctor = `-- name: ListWorkingHoursByDoctor :many
SELECT id, doctor_id, weekday, starts_at_local, ends_at_local
FROM doctor_working_hours
WHERE doctor_id = $1
ORDER BY weekday ASC, starts_at_local ASC
`

type ListWorkingHoursByDoctorRow struct {
	ID            uuid.UUID
	DoctorID      uuid.UUID
	Weekday       int16
	StartsAtLocal pgtype.Time
	EndsAtLocal   pgtype.Time
}

func (q *Queries) ListWorkingHoursByDoctor(ctx context.Context, doctorID uuid.UUID) ([]ListWorkingHoursByDoctorRow, error) {
	rows, err := q.db.Query(ctx, listWorkingHoursByDoctor, doctorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkingHoursByDoctorRow{}
	for rows.Next() {
		var i ListWorkingHoursByDoctorRow
		if err := rows.Scan(
			&i.ID,
			&i.DoctorID,
			&i.Weekday,
			&i.StartsAtLocal,
			&i.EndsAtLocal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
