// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createIdempotencyRecord = `-- name: CreateIdempotencyRecord :one
INSERT INTO idempotency_keys (
    patient_id, idempotency_key, request_fingerprint, appointment_id,
    response_status, response_body, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, patient_id, idempotency_key, request_fingerprint, appointment_id,
          response_status, response_body, created_at, expires_at
`

type CreateIdempotencyRecordParams struct {
	PatientID          uuid.UUID
	IdempotencyKey     string
	RequestFingerprint string
	AppointmentID      uuid.UUID
	ResponseStatus     int16
	ResponseBody       []byte
	ExpiresAt          time.Time
}

func (q *Queries) CreateIdempotencyRecord(ctx context.Context, arg CreateIdempotencyRecordParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyRecord,
		arg.PatientID,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.AppointmentID,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.AppointmentID,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredIdempotencyRecords = `-- name: DeleteExpiredIdempotencyRecords :execrows
DELETE FROM idempotency_keys
WHERE expires_at <= $1::timestamptz
`

func (q *Queries) DeleteExpiredIdempotencyRecords(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyRecords, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyRecord = `-- name: GetIdempotencyRecord :one
SELECT id, patient_id, idempotency_key, request_fingerprint, appointment_id,
       response_status, response_body, created_at, expires_at
FROM idempotency_keys
WHERE patient_id = $1 AND idempotency_key = $2
`

type GetIdempotencyRecordParams struct {
	PatientID      uuid.UUID
	IdempotencyKey string
}

func (q *Queries) GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyRecord, arg.PatientID, arg.IdempotencyKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.AppointmentID,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
