// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppointmentEventType string

const (
	AppointmentEventTypeBooked      AppointmentEventType = "booked"
	AppointmentEventTypeCancelled   AppointmentEventType = "cancelled"
	AppointmentEventTypeRescheduled AppointmentEventType = "rescheduled"
)

func (e *AppointmentEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppointmentEventType(s)
	case string:
		*e = AppointmentEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for AppointmentEventType: %T", src)
	}
	return nil
}

type NullAppointmentEventType struct {
	AppointmentEventType AppointmentEventType
	Valid                bool // Valid is true if AppointmentEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppointmentEventType) Scan(value interface{}) error {
	if value == nil {
		ns.AppointmentEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppointmentEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppointmentEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppointmentEventType), nil
}

type AppointmentStatus string

const (
	AppointmentStatusBooked    AppointmentStatus = "booked"
	AppointmentStatusCancelled AppointmentStatus = "cancelled"
)

func (e *AppointmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppointmentStatus(s)
	case string:
		*e = AppointmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppointmentStatus: %T", src)
	}
	return nil
}

type NullAppointmentStatus struct {
	AppointmentStatus AppointmentStatus
	Valid             bool // Valid is true if AppointmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppointmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppointmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppointmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppointmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppointmentStatus), nil
}

type Appointment struct {
	ID                 uuid.UUID
	DoctorID           uuid.UUID
	PatientID          uuid.UUID
	StartsAt           time.Time
	EndsAt             time.Time
	Status             AppointmentStatus
	CancellationReason *string
	CancelledAt        *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type AppointmentEvent struct {
	ID            int64
	AppointmentID uuid.UUID
	EventType     AppointmentEventType
	FromStartsAt  *time.Time
	ToStartsAt    *time.Time
	Source        string
	OccurredAt    time.Time
}

type Doctor struct {
	ID        uuid.UUID
	Slug      string
	FullName  string
	Specialty string
	Timezone  string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type DoctorWorkingHour struct {
	ID            uuid.UUID
	DoctorID      uuid.UUID
	Weekday       int16
	StartsAtLocal pgtype.Time
	EndsAtLocal   pgtype.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	MinuteRange   pgtype.Range[pgtype.Int4]
}

type IdempotencyKey struct {
	ID                 uuid.UUID
	PatientID          uuid.UUID
	IdempotencyKey     string
	RequestFingerprint string
	AppointmentID      uuid.UUID
	ResponseStatus     int16
	ResponseBody       []byte
	CreatedAt          time.Time
	ExpiresAt          time.Time
}

type Patient struct {
	ID        uuid.UUID
	FullName  string
	Email     string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
