// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patients.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countPatients = `-- name: CountPatients :one
SELECT count(*)
FROM patients
WHERE (NOT $1::boolean) OR is_active
`

func (q *Queries) CountPatients(ctx context.Context, activeOnly bool) (int64, error) {
	row := q.db.QueryRow(ctx, countPatients, activeOnly)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPatientByID = `-- name: GetPatientByID :one
SELECT id, full_name, email, is_active, created_at, updated_at
FROM patients
WHERE id = $1
`

func (q *Queries) GetPatientByID(ctx context.Context, id uuid.UUID) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatientByID, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPatients = `-- name: ListPatients :many
SELECT id, full_name, email, is_active, created_at, updated_at
FROM patients
WHERE (NOT $3::boolean) OR is_active
ORDER BY full_name ASC, id ASC
LIMIT $1 OFFSET $2
`

type ListPatientsParams struct {
	Limit      int32
	Offset     int32
	ActiveOnly bool
}

func (q *Queries) ListPatients(ctx context.Context, arg ListPatientsParams) ([]Patient, error) {
	rows, err := q.db.Query(ctx, listPatients, arg.Limit, arg.Offset, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patient{}
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
